language: ruby

rvm:
  - 2.2.3

gemfile:
  - ci/Gemfile.rails-4.1.x
  - ci/Gemfile.rails-4.2.x

env:
  - DB=sqlite
  - DB=mysql
  - DB=postgresql

script: bundle exec rake --trace

before_script:
  - mysql -e 'create database druthers_test'
  - psql -c 'create database druthers_test' -U postgres
